version: '3.8'

services:
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./example/templates:/templates
      - ./example/output:/output
    environment:
      - PORT=8080
      - TEMPLATES_DIR=/templates
      - OUTPUT_DIR=/output
    command: dev-server
    restart: unless-stopped

  generate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./example/templates:/templates
      - ./example/output:/output
    environment:
      - TEMPLATES_DIR=/templates
      - OUTPUT_DIR=/output
    command: generate 